interface McpToolDefinition {
  name: string;
  description: string;
  inputSchema: {
    type: 'object';
    properties: Record<string, unknown>;
    required?: string[];
  };
}

interface McpToolExport {
  tools: McpToolDefinition[];
  callTool: (name: string, args: Record<string, unknown>) => Promise<unknown>;
  meter?: { credits: number };
  cost?: Record<string, unknown>;
  provider?: string;
}

/**
 * EUR-Lex MCP — official EU law, article-level.
 *
 * Keyless. Two upstreams, both run by the EU Publications Office:
 *  - CELLAR content negotiation (publications.europa.eu/resource/celex/<CELEX>)
 *    returns the authentic XHTML of any act → article-level text + citations.
 *  - The CELLAR SPARQL endpoint (webapi/rdf/sparql) → search + metadata.
 *
 * Built for grounded compliance Q&A: resolve a regulation (GDPR, NIS2, DORA,
 * the EU AI Act, DSA/DMA, eIDAS, the Cyber Resilience Act …) to its CELEX id,
 * then quote a specific Article with a verifiable EUR-Lex citation URL.
 */


const CELLAR = 'http://publications.europa.eu/resource/celex';
const SPARQL = 'http://publications.europa.eu/webapi/rdf/sparql';
const RT = 'http://publications.europa.eu/resource/authority/resource-type';
const UA = 'pipeworx-mcp-eur-lex/1.0 (+https://pipeworx.io)';

/** Curated map of the EU digital/compliance corpus → CELEX. Lets an LLM resolve
 *  a common name to an id without knowing CELEX. Source of truth for aliases. */
const INDEX: Array<{
  alias: string;
  name: string;
  celex: string;
  type: string;
  date: string;
  summary: string;
}> = [
  { alias: 'GDPR', name: 'General Data Protection Regulation', celex: '32016R0679', type: 'Regulation', date: '2016-04-27', summary: 'EU-wide rules on processing of personal data and free movement of such data.' },
  { alias: 'NIS2', name: 'NIS2 Directive', celex: '32022L2555', type: 'Directive', date: '2022-12-14', summary: 'Measures for a high common level of cybersecurity across the Union; repeals NIS1.' },
  { alias: 'DORA', name: 'Digital Operational Resilience Act', celex: '32022R2554', type: 'Regulation', date: '2022-12-14', summary: 'Digital operational resilience for the financial sector (ICT risk, incident reporting, third-party risk).' },
  { alias: 'AI Act', name: 'Artificial Intelligence Act', celex: '32024R1689', type: 'Regulation', date: '2024-06-13', summary: 'Harmonised rules on artificial intelligence; risk-based obligations for AI systems and GPAI models.' },
  { alias: 'DSA', name: 'Digital Services Act', celex: '32022R2065', type: 'Regulation', date: '2022-10-19', summary: 'Single market for digital services; obligations for intermediaries and very large online platforms.' },
  { alias: 'DMA', name: 'Digital Markets Act', celex: '32022R1925', type: 'Regulation', date: '2022-09-14', summary: 'Contestable and fair markets in the digital sector; obligations for gatekeepers.' },
  { alias: 'eIDAS', name: 'eIDAS Regulation', celex: '32014R0910', type: 'Regulation', date: '2014-07-23', summary: 'Electronic identification and trust services for electronic transactions in the internal market.' },
  { alias: 'eIDAS 2.0', name: 'European Digital Identity Framework', celex: '32024R1183', type: 'Regulation', date: '2024-04-11', summary: 'Amends eIDAS to establish the European Digital Identity Wallet framework.' },
  { alias: 'Cyber Resilience Act', name: 'Cyber Resilience Act', celex: '32024R2847', type: 'Regulation', date: '2024-10-23', summary: 'Horizontal cybersecurity requirements for products with digital elements.' },
  { alias: 'Cybersecurity Act', name: 'Cybersecurity Act', celex: '32019R0881', type: 'Regulation', date: '2019-04-17', summary: 'ENISA mandate and an EU cybersecurity certification framework for ICT products/services.' },
  { alias: 'Data Act', name: 'Data Act', celex: '32023R2854', type: 'Regulation', date: '2023-12-13', summary: 'Harmonised rules on fair access to and use of data generated by connected products.' },
  { alias: 'Data Governance Act', name: 'Data Governance Act', celex: '32022R0868', type: 'Regulation', date: '2022-05-30', summary: 'Framework for data sharing, data intermediation services and data altruism.' },
  { alias: 'ePrivacy', name: 'ePrivacy Directive', celex: '32002L0058', type: 'Directive', date: '2002-07-12', summary: 'Privacy and electronic communications (cookies, confidentiality, traffic data).' },
  { alias: 'Machinery Regulation', name: 'Machinery Regulation', celex: '32023R1230', type: 'Regulation', date: '2023-06-14', summary: 'Health and safety requirements for machinery, including AI-related safety components.' },
];

const tools: McpToolExport['tools'] = [
  {
    name: 'compliance_index',
    description:
      'Resolve a common EU regulation name to its CELEX id. Returns the curated map of the EU digital/compliance corpus (GDPR, NIS2, DORA, AI Act, DSA, DMA, eIDAS, Cyber Resilience Act, Data Act, …) with CELEX ids, types, dates and one-line summaries. Use this first to turn a name like "GDPR" into the CELEX id the other tools need.',
    inputSchema: {
      type: 'object' as const,
      properties: {
        query: { type: 'string', description: 'Optional filter — name/alias/keyword (e.g. "AI Act", "data"). Omit to list the whole corpus.' },
      },
    },
  },
  {
    name: 'search_legislation',
    description:
      'Full-text search of EU legislation titles via the EUR-Lex SPARQL endpoint. Returns CELEX id, English title and document date. Use when the act is not in compliance_index, or to find related/amending acts.',
    inputSchema: {
      type: 'object' as const,
      properties: {
        query: { type: 'string', description: 'Keyword(s) that must appear in the English title, e.g. "cybersecurity certification".' },
        type: { type: 'string', enum: ['regulation', 'directive', 'decision'], description: 'Optional: restrict to a legal act type.' },
        limit: { type: 'number', description: 'Max results (default 10, max 25).' },
      },
      required: ['query'],
    },
  },
  {
    name: 'get_metadata',
    description:
      'Metadata notice for one act by CELEX id: title, document date, legal type, in-force status hint and the EUR-Lex citation URL. Cheap; does not download the full text.',
    inputSchema: {
      type: 'object' as const,
      properties: {
        celex: { type: 'string', description: 'CELEX id, e.g. "32016R0679", or a known alias like "GDPR".' },
        lang: { type: 'string', description: 'ISO 639-2/B language code for the title (default "eng": eng, fra, deu, spa, ita, …).' },
      },
      required: ['celex'],
    },
  },
  {
    name: 'list_articles',
    description:
      'Table of contents for an act: every Article number and its heading. Use to discover which Article to quote before calling get_article.',
    inputSchema: {
      type: 'object' as const,
      properties: {
        celex: { type: 'string', description: 'CELEX id or a known alias (e.g. "DORA").' },
        lang: { type: 'string', description: 'ISO 639-2/B language code (default "eng").' },
      },
      required: ['celex'],
    },
  },
  {
    name: 'get_article',
    description:
      'Full text of one or more Articles of an act, with a verifiable EUR-Lex citation URL for each. THE article-level grounding tool: quote GDPR Art. 17, AI Act Art. 6, etc. Accepts a single number ("17"), a comma list ("5,6,17") or a range ("5-9").',
    inputSchema: {
      type: 'object' as const,
      properties: {
        celex: { type: 'string', description: 'CELEX id or a known alias (e.g. "GDPR").' },
        article: { type: 'string', description: 'Article selector: "17", "5,6,17", or "5-9". Suffixed numbers like "9a" are supported.' },
        lang: { type: 'string', description: 'ISO 639-2/B language code (default "eng").' },
      },
      required: ['celex', 'article'],
    },
  },
  {
    name: 'get_document',
    description:
      'Plain-text of a whole act (recitals + enacting terms), paged. Use for short acts or to read recitals/definitions; for a specific Article prefer get_article. Returns up to max_chars from offset.',
    inputSchema: {
      type: 'object' as const,
      properties: {
        celex: { type: 'string', description: 'CELEX id or a known alias.' },
        lang: { type: 'string', description: 'ISO 639-2/B language code (default "eng").' },
        max_chars: { type: 'number', description: 'Max characters to return (default 8000, max 40000).' },
        offset: { type: 'number', description: 'Character offset to start from, for paging (default 0).' },
      },
      required: ['celex'],
    },
  },
];

/* ---------- helpers ---------- */

function resolveCelex(input: string): string {
  const raw = String(input ?? '').trim();
  const hit = INDEX.find(
    (e) => e.alias.toLowerCase() === raw.toLowerCase() || e.name.toLowerCase() === raw.toLowerCase(),
  );
  if (hit) return hit.celex;
  return raw.toUpperCase().replace(/\s+/g, '');
}

function langCode(input: unknown): string {
  const l = String(input ?? 'eng').trim().toLowerCase();
  return /^[a-z]{3}$/.test(l) ? l : 'eng';
}

function celexUrl(celex: string, anchor?: string): string {
  const base = `https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:${celex}`;
  return anchor ? `${base}#${anchor}` : base;
}

const ENTITIES: Record<string, string> = {
  '&nbsp;': ' ', '&amp;': '&', '&lt;': '<', '&gt;': '>', '&quot;': '"', '&#39;': "'",
  '&apos;': "'", '&mdash;': '—', '&ndash;': '–', '&laquo;': '«', '&raquo;': '»',
};

function decodeEntities(s: string): string {
  return s
    .replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCodePoint(parseInt(h, 16)))
    .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(parseInt(d, 10)))
    .replace(/&[a-z]+;/gi, (m) => ENTITIES[m] ?? m);
}

/** Convert a slice of EUR-Lex XHTML to readable plain text. */
function htmlToText(html: string): string {
  return decodeEntities(
    html
      .replace(/<\/(p|div|tr|h[1-6]|li)>/gi, '\n')
      .replace(/<\/td>/gi, ' ')
      .replace(/<br\s*\/?>/gi, '\n')
      .replace(/<[^>]+>/g, '')
      .replace(/[ \t]+/g, ' ')
      .replace(/ *\n */g, '\n')
      .replace(/\n{3,}/g, '\n\n'),
  ).trim();
}

// Bounded module-level cache so list→get on the same act doesn't refetch ~800KB.
const docCache = new Map<string, string>();

async function fetchDocument(celex: string, lang: string): Promise<string> {
  const key = `${celex}:${lang}`;
  const cached = docCache.get(key);
  if (cached) return cached;
  const res = await fetch(`${CELLAR}/${celex}`, {
    headers: { Accept: 'application/xhtml+xml', 'Accept-Language': lang, 'User-Agent': UA },
  });
  if (res.status === 404) throw new Error(`EUR-Lex: no document for CELEX ${celex} (lang ${lang}). Check the id with search_legislation.`);
  if (!res.ok) throw new Error(`EUR-Lex CELLAR: ${res.status} ${(await res.text()).slice(0, 160)}`);
  const html = await res.text();
  if (docCache.size > 4) docCache.clear();
  docCache.set(key, html);
  return html;
}

/** Index article divs by their start offset. Matches id="art_<n>" exactly,
 *  excluding the sub-anchors like id="art_5.tit_1". `start` points just past
 *  the enclosing tag's `>` so a slice never carries a dangling attribute. */
function articleSpans(html: string): Array<{ num: string; start: number }> {
  const re = /id="art_([0-9]+[a-z]*)"/gi;
  const spans: Array<{ num: string; start: number }> = [];
  let m: RegExpExecArray | null;
  while ((m = re.exec(html)) !== null) {
    const gt = html.indexOf('>', m.index);
    spans.push({ num: m[1], start: gt === -1 ? m.index : gt + 1 });
  }
  return spans;
}

function articleTitle(block: string): string {
  const m = block.match(/class="oj-sti-art"[^>]*>([\s\S]*?)<\/p>/i);
  return m ? decodeEntities(m[1].replace(/<[^>]+>/g, '').trim()) : '';
}

function expandSelector(sel: string): string[] {
  const out: string[] = [];
  for (const part of String(sel).split(',').map((s) => s.trim()).filter(Boolean)) {
    const range = part.match(/^(\d+)\s*-\s*(\d+)$/);
    if (range) {
      const a = parseInt(range[1], 10), b = parseInt(range[2], 10);
      for (let i = a; i <= b && i - a < 50; i++) out.push(String(i));
    } else {
      out.push(part.toLowerCase());
    }
  }
  return [...new Set(out)];
}

async function sparql(query: string): Promise<any> {
  const res = await fetch(SPARQL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', Accept: 'application/sparql-results+json', 'User-Agent': UA },
    body: new URLSearchParams({ query, format: 'application/sparql-results+json' }).toString(),
  });
  if (!res.ok) throw new Error(`EUR-Lex SPARQL: ${res.status} ${(await res.text()).slice(0, 160)}`);
  return res.json();
}

/* ---------- tool dispatch ---------- */

async function callTool(name: string, args: Record<string, unknown>): Promise<unknown> {
  switch (name) {
    case 'compliance_index': {
      const q = String(args.query ?? '').trim().toLowerCase();
      const rows = q
        ? INDEX.filter((e) =>
            (e.alias + ' ' + e.name + ' ' + e.summary).toLowerCase().includes(q),
          )
        : INDEX;
      return {
        count: rows.length,
        regulations: rows.map((e) => ({ ...e, citation_url: celexUrl(e.celex) })),
        note: 'Pass a CELEX id (or these aliases) to get_article / list_articles / get_document.',
      };
    }

    case 'search_legislation': {
      const q = String(args.query ?? '').trim().toLowerCase().replace(/["\\]/g, '');
      if (!q) throw new Error('query is required.');
      const limit = Math.min(Math.max(Number(args.limit) || 10, 1), 25);
      const typeMap: Record<string, string> = { regulation: 'REG', directive: 'DIR', decision: 'DEC' };
      const typeStr = typeMap[String(args.type ?? '').toLowerCase()];
      const typeFilter = typeStr ? `?w <http://publications.europa.eu/ontology/cdm#work_has_resource-type> <${RT}/${typeStr}> .` : '';
      const query = `PREFIX cdm: <http://publications.europa.eu/ontology/cdm#>
SELECT DISTINCT ?celex ?title ?date WHERE {
  ?w cdm:resource_legal_id_celex ?celex .
  ?expr cdm:expression_belongs_to_work ?w ;
        cdm:expression_uses_language <http://publications.europa.eu/resource/authority/language/ENG> ;
        cdm:expression_title ?title .
  OPTIONAL { ?w cdm:work_date_document ?date . }
  ${typeFilter}
  FILTER(CONTAINS(LCASE(STR(?title)), "${q}"))
} ORDER BY DESC(?date) LIMIT ${limit}`;
      const json = await sparql(query);
      const results = (json?.results?.bindings ?? []).map((b: any) => ({
        celex: b.celex?.value,
        title: b.title?.value,
        date: b.date?.value ?? null,
        citation_url: celexUrl(b.celex?.value),
      }));
      return { query: q, count: results.length, results };
    }

    case 'get_metadata': {
      const celex = resolveCelex(String(args.celex ?? ''));
      const lang = langCode(args.lang);
      const res = await fetch(`${CELLAR}/${celex}`, {
        headers: { Accept: 'application/xml;notice=object', 'Accept-Language': lang, 'User-Agent': UA },
      });
      if (res.status === 404) throw new Error(`EUR-Lex: no act for CELEX ${celex}. Try search_legislation.`);
      if (!res.ok) throw new Error(`EUR-Lex: ${res.status} ${(await res.text()).slice(0, 160)}`);
      const xml = await res.text();
      const pick = (tag: string) => {
        const m = xml.match(new RegExp(`<${tag}[^>]*>([\\s\\S]*?)</${tag}>`, 'i'));
        return m ? decodeEntities(m[1].replace(/<[^>]+>/g, '').trim()) : null;
      };
      const indexed = INDEX.find((e) => e.celex === celex);
      return {
        celex,
        title: pick('EXPRESSION_TITLE') ?? pick('TITLE') ?? indexed?.name ?? null,
        date_document: pick('WORK_DATE_DOCUMENT') ?? indexed?.date ?? null,
        type: indexed?.type ?? pick('WORK_HAS_RESOURCE-TYPE') ?? null,
        alias: indexed?.alias ?? null,
        summary: indexed?.summary ?? null,
        citation_url: celexUrl(celex),
      };
    }

    case 'list_articles': {
      const celex = resolveCelex(String(args.celex ?? ''));
      const lang = langCode(args.lang);
      const html = await fetchDocument(celex, lang);
      const spans = articleSpans(html);
      const articles = spans.map((s, i) => {
        const block = html.slice(s.start, spans[i + 1]?.start ?? html.length);
        return { article: s.num, heading: articleTitle(block), citation_url: celexUrl(celex, `art_${s.num}`) };
      });
      if (!articles.length) throw new Error(`EUR-Lex: no Articles parsed for CELEX ${celex} — the act may have a non-standard structure or wrong id.`);
      return { celex, count: articles.length, articles };
    }

    case 'get_article': {
      const celex = resolveCelex(String(args.celex ?? ''));
      const lang = langCode(args.lang);
      const wanted = expandSelector(String(args.article ?? ''));
      if (!wanted.length) throw new Error('article is required, e.g. "17", "5,6,17" or "5-9".');
      const html = await fetchDocument(celex, lang);
      const spans = articleSpans(html);
      const byNum = new Map(spans.map((s, i) => [s.num.toLowerCase(), { ...s, end: spans[i + 1]?.start ?? html.length }]));
      const articles = wanted.map((num) => {
        const span = byNum.get(num);
        if (!span) return { article: num, found: false, text: null, heading: null, citation_url: celexUrl(celex, `art_${num}`) };
        const block = html.slice(span.start, span.end);
        return {
          article: num,
          found: true,
          heading: articleTitle(block),
          text: htmlToText(block),
          citation_url: celexUrl(celex, `art_${num}`),
        };
      });
      return { celex, requested: wanted, articles };
    }

    case 'get_document': {
      const celex = resolveCelex(String(args.celex ?? ''));
      const lang = langCode(args.lang);
      const maxChars = Math.min(Math.max(Number(args.max_chars) || 8000, 500), 40000);
      const offset = Math.max(Number(args.offset) || 0, 0);
      const html = await fetchDocument(celex, lang);
      // Strip the masthead/script noise, keep the enacting body.
      const body = html.replace(/<head[\s\S]*?<\/head>/i, '').replace(/<script[\s\S]*?<\/script>/gi, '');
      const text = htmlToText(body);
      const slice = text.slice(offset, offset + maxChars);
      return {
        celex,
        total_chars: text.length,
        offset,
        returned_chars: slice.length,
        has_more: offset + maxChars < text.length,
        next_offset: offset + maxChars < text.length ? offset + maxChars : null,
        citation_url: celexUrl(celex),
        text: slice,
      };
    }

    default:
      throw new Error(`Unknown tool: ${name}`);
  }
}

export default { tools, callTool, meter: { credits: 1 } } satisfies McpToolExport;
